// KOREA UNIVERSITY OF TECHNOLOGY AND EDUCATION
// EMBBEDDED APPLICATION AND PRACTICE
// SPRING TERM PROJECT BASED ON RASPBERRY PI
// COMPUTER SCIENCE AND ENGINEERING 2012136116
// JAEU JEONG

#include <stdio.h>
